---
- name: restart sshd
  block:
    - shell: /usr/sbin/sshd -t
    - systemd:
        name: sshd
        enabled: yes
        state: restarted
# from https://github.com/chmduquesne/ansible-iptables-persistent
- name: save iptables v4 rules
  shell: iptables-save > /etc/iptables/rules.v4
  listen: persist iptables
- name: save iptables v6 rules
  shell: ip6tables-save > /etc/iptables/rules.v6
  listen: persist iptables
